services:
  - type: web
    name: sipa-backend
    env: docker
    plan: free
    dockerContext: backend
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: DATABASE_TYPE
        value: json
      - key: PORT
        value: 4000

